//For application use
#pragma once
#include <K-Engine/Application.h>
#include <K-Engine/Window.h>
#include <K-Engine/GameObject.h>
#include <K-Engine/Material.h>
#include <K-Engine/Editor.h>
#include <K-Engine/Scene.h>
#include <K-Engine/SceneManager.h>
#include <K-Engine/Time.h>
#include <K-Engine/Component.h>
#include <K-Engine/Texture.h>
#include <K-Engine/Transform.h>
#include <K-Engine/Mesh.h>
#include <K-Engine/Sprite.h>
#include <K-Engine/InputManager.h>
#include <K-Engine/Camera.h>
#include <K-Engine/Player.h>
#include <K-Engine/Serializer.h>
#include <K-Engine/Timer.h>
#include <K-Engine/Move.h>
#include <K-Engine/TriggerDeath.h>
#include <K-Engine/Light.h>
#include <K-Engine/Shooter.h>
#include <K-Engine/Crush.h>
#include <K-Engine/TriggerNextScene.h>
#include <K-Engine/ButtonLoadScene.h>