//For application use
#pragma once
#include <K-Engine/Application.h>
#include <K-Engine/Window.h>
#include <K-Engine/GameObject.h>
#include <K-Engine/Material.h>
#include <K-Engine/Editor.h>
#include <K-Engine/Scene.h>
#include <K-Engine/SceneManager.h>
#include <K-Engine/Time.h>
#include <K-Engine/Texture.h>
#include <K-Engine/Transform.h>
#include <K-Engine/InputManager.h>
#include <K-Engine/Serializer.h>
#include <K-Engine/Components/Component.h>
#include <K-Engine/Components/Mesh.h>
#include <K-Engine/Components/Sprite.h>
#include <K-Engine/Components/Camera.h>
#include <K-Engine/Components/Player.h>
#include <K-Engine/Components/Timer.h>
#include <K-Engine/Components/Move.h>
#include <K-Engine/Components/TriggerDeath.h>
#include <K-Engine/Components/Light.h>
#include <K-Engine/Components/Shooter.h>
#include <K-Engine/Components/Crush.h>
#include <K-Engine/Components/TriggerNextScene.h>
#include <K-Engine/Components/ButtonLoadScene.h>
#include <K-Engine/Components/Quit.h>